---
- name: Start with the Common-Packer Baseline
  import_playbook: ../common-packer/provision/baseline.yaml

- name: Layer IoTivity requirements on top
  hosts: all
  become: true
  roles:
    - { role: iotivity, when: ansible_distribution == "Ubuntu" }
